"""
Django settings for miproyecto project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
# pymysql: el conector que instalaste en el paso 02
import pymysql
# Hace que Django use pymysql como si fuera el driver oficial de MySQL para Python
pymysql.install_as_MySQLdb()

# config: función de python-decouple que lee valores del archivo .env
# Csv: convierte un valor separado por comas del .env en una lista de Python
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECRET_KEY: ya no queda escrita en el código — se lee del .env / de Render
SECRET_KEY = config('SECRET_KEY')

# DEBUG: default=False es la opción segura si la variable no está definida
# cast=bool convierte el texto "True"/"False" del .env en un booleano real de Python
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS: lista de dominios que Django acepta atender; Csv() la separa por comas
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())


# Application definition

INSTALLED_APPS = [
    # apps que Django trae instaladas por defecto (admin, auth, sessions, etc.)
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'core': tu app nueva, agregada al final de la lista
    'core',
]

MIDDLEWARE = [
    # SecurityMiddleware: agrega cabeceras de seguridad básicas a cada respuesta
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoiseMiddleware: nueva línea — debe ir justo después de SecurityMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',
    # SessionMiddleware: habilita las sesiones (login, carrito, etc.)
    'django.contrib.sessions.middleware.SessionMiddleware',
    # CommonMiddleware: ajustes generales de peticiones/respuestas
    'django.middleware.common.CommonMiddleware',
    # CsrfViewMiddleware: protege los formularios contra ataques CSRF
    'django.middleware.csrf.CsrfViewMiddleware',
    # AuthenticationMiddleware: asocia cada petición con el usuario logueado (si hay uno)
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # MessageMiddleware: habilita mensajes flash de una sola vista (ej. "guardado con éxito")
    'django.contrib.messages.middleware.MessageMiddleware',
    # XFrameOptionsMiddleware: evita que tu sitio se cargue dentro de un <iframe> ajeno
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# STATIC_ROOT: carpeta donde collectstatic junta todos los archivos estáticos antes de publicar
STATIC_ROOT = BASE_DIR / 'staticfiles'

# STORAGES: le dice a Django que use whitenoise para comprimir y versionar esos archivos
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    # cierre de la config de "staticfiles"
    },
# cierre del diccionario STORAGES
}

ROOT_URLCONF = 'miproyecto.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'miproyecto.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# (más abajo en el archivo, reemplazá el DATABASES que trae Django por defecto)
DATABASES = {
    'default': {
        # ENGINE: qué motor de base de datos usar — mysql en vez del sqlite3 por defecto
        'ENGINE': 'django.db.backends.mysql',
        # NAME: nombre de la base de datos, leído de la variable DB_NAME del .env
        'NAME': config('DB_NAME'),
        # USER: usuario de conexión, leído de DB_USER
        'USER': config('DB_USER'),
        # PASSWORD: contraseña de conexión, leída de DB_PASSWORD
        'PASSWORD': config('DB_PASSWORD'),
        # HOST: servidor donde vive la base de datos, leído de DB_HOST
        'HOST': config('DB_HOST'),
        # PORT: puerto de conexión; default='3306' se usa solo si DB_PORT no está en el .env
        'PORT': config('DB_PORT', default='3306'),
        # OPTIONS: Aiven exige que la conexión venga cifrada (SSL)
        'OPTIONS': {'ssl': {'ssl-mode': 'REQUIRED'}},
    # cierre del diccionario de configuración de la conexión
    }
# cierre del diccionario DATABASES
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
